version: '3'
services:
  deploy:
    image: openjdk:11.0.7-jdk 
    container_name: deploy
    privileged: true
    environment:
       DL_ROLLBACK: 'gmic-cad-artifact-1.0.0-standalone.jar'
    volumes:
      - /home/xing/cinema/api:/webapps
      - ./api/lib:/webapps/lib
      - ./scripts/docker-entrypoint.sh:/webapps/docker-entrypoint.sh
    working_dir: /webapps
    # entrypoint:
    #  - sh /webapps/docker-entrypoint.sh
    command: "sh /webapps/docker-entrypoint.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

